[FORMAT "WCOFF"]
[INSTRSET "i486p"]
[OPTIMIZE 1]
[OPTION 1]
[BITS 32]
[FILE "kernelC.c"]
[SECTION .text]
	ALIGN	2
	GLOBAL	_NNOSMain
_NNOSMain:
	PUSH	EBP
	MOV	EBP,ESP
	SUB	ESP,4
	MOV	DWORD [-4+EBP],0
	MOV	DWORD [-4+EBP],0
L2:
	CMP	DWORD [-4+EBP],10
	JLE	L5
	JMP	L3
L5:
	MOV	EAX,DWORD [-4+EBP]
	ADD	EAX,755584
	MOV	BYTE [EAX],99
	MOV	EAX,DWORD [-4+EBP]
	ADD	EAX,755585
	MOV	BYTE [EAX],12
	LEA	EAX,DWORD [-4+EBP]
	INC	DWORD [EAX]
	LEA	EAX,DWORD [-4+EBP]
	INC	DWORD [EAX]
	JMP	L2
L3:
L6:
	JMP	L6
