TARGET     = bim2nex
MODE       = exe
OBJS       = $(TARGET).obj
STACKSIZE  = 0x1000000 # 16MB (default)

INCPATH    = ../../../tools/win32/
CC1OPT     = -Dmain=main0
include ../../../tools/com_mak.txt
